-- SteppeUp — schema hardening (run once in Supabase SQL Editor)
-- Fixes the two silent failure modes found during the 2026-07-04 audit:
--
-- 1. jobs.source_id may lack a UNIQUE constraint. upsert(..., onConflict:
--    'source_id') REQUIRES one; without it every batch errors (42P10) and the
--    scraper "succeeds" while writing nothing.
-- 2. scraping_logs is missing the columns the scrapers write, so run logging
--    has silently failed forever (it's wrapped in try/catch).
--
-- Both statements are idempotent — safe to run repeatedly.

-- 1) Unique index for upsert conflict target
CREATE UNIQUE INDEX IF NOT EXISTS jobs_source_id_key ON public.jobs (source_id);

-- 2) Bring scraping_logs up to what the code writes
CREATE TABLE IF NOT EXISTS public.scraping_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.scraping_logs ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE public.scraping_logs ADD COLUMN IF NOT EXISTS jobs_found INTEGER;
ALTER TABLE public.scraping_logs ADD COLUMN IF NOT EXISTS jobs_removed INTEGER;
ALTER TABLE public.scraping_logs ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE public.scraping_logs ADD COLUMN IF NOT EXISTS details JSONB;

-- 3) SECURITY: make sure anon (the key shipped in index.html) can only READ.
--    RLS on + a read-only policy for active jobs. The scraper uses the service
--    key, which bypasses RLS, so nothing breaks.
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon can read active jobs" ON public.jobs;
CREATE POLICY "anon can read active jobs" ON public.jobs
  FOR SELECT TO anon USING (true);
-- No INSERT/UPDATE/DELETE policies for anon = writes denied.

ALTER TABLE public.scraping_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon can read logs" ON public.scraping_logs;
CREATE POLICY "anon can read logs" ON public.scraping_logs
  FOR SELECT TO anon USING (true);
